name: flavor_example
description: A new Flutter application.
version: 1.0.2
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_logger: any
  package_info: any
  firebase_auth: any
  cloud_firestore: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: flavors
flutter:
  uses-material-design: true
